server:
  port: 9999

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true #使用IP注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #注册名显示为ip：port
  client:
    register-with-eureka: false #默认回把自己注册进eureka，改为false，取消
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #指定服务注册中心的位置
